### ISSUE TITLE
Identical Energy Component Graphs for Complex and Receptor in FreeEnergyPlot.py

### ISSUE THREAD

**Issue by Mesia-pixel** [hypowergravity/FreeEnergyPlot#1]
Hi,
I am using the FreeEnergyPlot.py script to analyze per-residue energy decomposition for my protein-ligand complex. However, I noticed that the energy component graphs for the complex (delta_energy_bar_plot_receptor and delta_enery_bar_plot_complex) and the receptor are identical, which seems incorrect. I used the script as provided in the repository and I ensured that I provided the correct prmtop file and residue list. Despite this, the generated graphs for the complex and receptor are exactly the same, which shouldn't be the case as the energy components for the complex and the receptor should differ. I noticed that the images you reported in the script's example are also the same for the protein and the complex. Could you please explain why this is happening?

**Comment by hypowergravity** [comment]
Hi,

The image of the complex and receptor contribution might not be identical but somewhat similar, given that the contribution of the ligand will be small compared to the receptor. You can check the values in the FINAL_RESULTS_MMPBSA.dat file. The script just plot what you would get after running the calculations. Since the magnitude of the contribution in the complex and protein are similar and the ligand is very minimal, it might look alike, but there will be slight changes.

**Comment by Mesia-pixel** [comment]
Dear Sriram,
I hope this message finds you well. I am writing to seek clarification
regarding the axes representation in the graphs generated from the CSV file
named “all-decomp_energy_terms.csv.” Specifically, I would like to
understand which columns from this CSV file are read and plotted. In my
graphs, the values range from -2 to +3, and I would like to comprehend the
basis on which these bar plots are generated. Additionally, could you
please confirm if the energy values are expressed in kilocalories (Kcal)?
Thank you very much for your assistance.
 Best regards,

Alessandra

**Comment by hypowergravity** [comment]
Yes, the energy is in kcal/mol. 
Can you send images give a detailed description.

**Comment by Mesia-pixel** [comment]
I wanted to know if the values plotted are from the CSV files generated by
the analysis, specifically all-decomp_energy_terms.csv,
all_energy_terms.csv, or the file final_decomp_mmgbsa.dat. From a quick
look, it seems there are more values within a range of -2/+3. If you want,
I can send these files

**Comment by hypowergravity** [comment]
I am not sure what you mean by "more values". 

I am not sure what you have changed, the command in readme.md do not produce "all-decomp_energy_terms.csv" or "all-decomp_energy_terms.csv".

The script uses MMPBSA_API to plot the saved data after the calculation is done in amber.
